### ISSUE TITLE
Non zero cost

### ISSUE THREAD

**Issue by OBorce** [contextfreecode/abstractions#1]
The non zero cost is because in the abstractions you have an extra addition to 0, because of the starting with 0 and adding to it, which for floating numbers can't be optimized because of negative -0, which with addition with +0 will be +0.

So to get the same assembly you can either initialize the initial sum to the product of the first element, or use `-ffast-math` in C++
Or add an 0 in your hand crafted one. `std::sqrt(0 + x * x + y * y);`

**Comment by tjpalmer** [comment]
Thanks for the tips! I've [pushed a new commit](https://github.com/contextfreecode/abstractions/commit/116ffaea586f65d4131d2f4521b6e2da3514281b) with the "initialize to first element" recommendation.
